from PIL import Image
import streamlit as st

st.title('Caza y Pesca')

st.sidebar.header('SPOTS')

st.set_option('deprecation.showPyplotGlobalUse', False)
preflop_selector = st.sidebar.radio('Opciones', ('OR','ROL','3Bet-Call','Call3Bet-4Bet','3Bet-Call-Multiway','Cold4Bet','VS Cold4Bet'))


if preflop_selector == 'OR':
    open_raise = Image.open('OPEN_RAISE.png')
    st.image(open_raise, use_column_width=500)
    st.pyplot()
    
if preflop_selector == 'ROL':
    st.header('ROL: Desde BB')
    rol_bar1 = st.beta_expander('ROL: BB vs BTN-CO (FISH)')
    bb_rol1 = Image.open('ROL_BBvsBTN-CO(FISH).png')
    rol_bar1.image(bb_rol1, use_column_width=500)
    rol_bar2 = st.beta_expander('ROL: BB vs BTN-CO (REG)')
    bb_rol2 = Image.open('ROL_BBvsBTN-CO(REG).png')
    rol_bar2.image(bb_rol2, use_column_width=500)
    rol_bar3 = st.beta_expander('ROL: BB vs SB (FISH)')
    bb_rol3 = Image.open('ROL_BBvsSB(FISH).png')
    rol_bar3.image(bb_rol3, use_column_width=500)
    rol_bar4 = st.beta_expander('ROL: BB vs SB (REG)')
    bb_rol4 = Image.open('ROL_BBvsSB(REG).png')
    rol_bar4.image(bb_rol4, use_column_width=500)
    st.header('ROL: Desde SB')
    rol_bar5 = st.beta_expander('ROL: SB vs BTN-CO (FISH)')
    sb_rol5 = Image.open('ROL_SBvsBTN-CO(FISH).png')
    rol_bar5.image(sb_rol5, use_column_width=500)
    rol_bar6 = st.beta_expander('ROL: SB vs EP (FISH)')
    sb_rol6 = Image.open('ROL_SBvsBTN-CO(REG).png')
    rol_bar6.image(sb_rol6, use_column_width=500)
    st.header('ROL: Desde BTN+')
    rol_bar7 = st.beta_expander('ROL: MP vs EP (FISH)')
    btn_rol7 = Image.open('ROL_MPvsEP(FISH).png')
    rol_bar7.image(btn_rol7, use_column_width=500)
    rol_bar8 = st.beta_expander('ROL: CO vs EP (FISH)')
    btn_rol8 = Image.open('ROL_COvsEP(FISH).png')
    rol_bar8.image(btn_rol8, use_column_width=500)
    rol_bar9 = st.beta_expander('ROL: BTN vs CO-EP (FISH)')
    btn_rol9 = Image.open('ROL_BTNvsCO-EP(FISH).png')
    rol_bar9.image(btn_rol9, use_column_width=500)
    st.pyplot()
    
if preflop_selector == '3Bet-Call':
    st.header('3BET-CALL: Desde BB')
    tbet_bar = st.beta_expander('3BET-CALL: BB vs SB')
    tbet = Image.open('3BET-CALL_BBvsSB.png')
    tbet_bar.image(tbet, use_column_width=500)
    tbet_bar1 = st.beta_expander('3BET-CALL: BB vs BTN')
    tbet1 = Image.open('3BET-CALL_BBvsBTN.png')
    tbet_bar1.image(tbet1, use_column_width=500)
    tbet_bar2 = st.beta_expander('3BET-CALL: BB vs CO')
    tbet2 = Image.open('3BET-CALL_BBvsCO.png')
    tbet_bar2.image(tbet2, use_column_width=500)
    tbet_bar3 = st.beta_expander('3BET-CALL: BB vs EP')
    tbet3 = Image.open('3BET-CALL_BBvsEARLY.png')
    tbet_bar3.image(tbet3, use_column_width=500)
    st.header('3BET-CALL: Desde SB')
    tbet_bar4 = st.beta_expander('3BET-CALL: SB vs BTN')
    tbet4 = Image.open('3BET-CALL_SBvsBTN.png')
    tbet_bar4.image(tbet4, use_column_width=500)
    tbet_bar5 = st.beta_expander('3BET-CALL: SB vs CO')
    tbet5 = Image.open('3BET-CALL_SBvsCO.png')
    tbet_bar5.image(tbet5, use_column_width=500)
    tbet_bar6 = st.beta_expander('3BET-CALL: SB vs EP')
    tbet6 = Image.open('3BET-CALL_SBvsEARLY.png')
    tbet_bar6.image(tbet6, use_column_width=500)
    st.header('3BET-CALL: Desde BTN')
    tbet_bar7 = st.beta_expander('3BET-CALL: BTN vs CO')
    tbet7 = Image.open('3BET-CALL_BTNvsCO.png')
    tbet_bar7.image(tbet7, use_column_width=500)
    tbet_bar8 = st.beta_expander('3BET-CALL: BTN vs EP')
    tbet8 = Image.open('3BET-CALL_BTNvsEARLY.png')
    tbet_bar8.image(tbet8, use_column_width=500)
    st.header('3BET-CALL: Desde CO')
    tbet_bar9 = st.beta_expander('3BET-CALL: CO vs EP')
    tbet9 = Image.open('3BET-CALL_COvsEARLY.png')
    tbet_bar9.image(tbet9, use_column_width=500)
    st.header('3BET-CALL: Desde MP')
    tbet_bar10 = st.beta_expander('3BET-CALL: MP vs UTG')
    tbet10 = Image.open('3BET-CALL_MPvsEARLY.png')
    tbet_bar10.image(tbet10, use_column_width=500)
    st.pyplot()

if preflop_selector == '3Bet-Call-Multiway':
    st.header('3BET-CALL: Desde BB')
    tmbet_bar = st.beta_expander('3BET-CALL-MULTIWAY: BB vs SB vs BTN')
    tmbet = Image.open('3BET-CALL_MULTIWAY_BBvsSBvsBTN.png')
    tmbet_bar.image(tmbet, use_column_width=500)
    tmbet_bar1 = st.beta_expander('3BET-CALL-MULTIWAY: BB vs SB vs CO')
    tmbet1 = Image.open('3BET-CALL_MULTIWAY_BBvsSBvsCO.png')
    tmbet_bar1.image(tmbet1, use_column_width=500)
    tmbet_bar2 = st.beta_expander('3BET-CALL-MULTIWAY: BB vs SB vs EP')
    tmbet2 = Image.open('3BET-CALL_MULTIWAY_BBvsSBvsEP.png')
    tmbet_bar2.image(tmbet2, use_column_width=500)
    tmbet_bar3 = st.beta_expander('3BET-CALL-MULTIWAY: BB vs BTN vs CO')
    tmbet3 = Image.open('3BET-CALL_MULTIWAY_BBvsBTNvsCO.png')
    tmbet_bar3.image(tmbet3, use_column_width=500)
    tmbet_bar4 = st.beta_expander('3BET-CALL-MULTIWAY: BB vs BTN vs EP')
    tmbet4 = Image.open('3BET-CALL_MULTIWAY_BBvsBTNvsEP.png')
    tmbet_bar4.image(tmbet4, use_column_width=500)
    tmbet_bar5 = st.beta_expander('3BET-CALL-MULTIWAY: BB vs MP vs UTG')
    tmbet5 = Image.open('3BET-CALL_MULTIWAY_BBvsMPvsUTG.png')
    tmbet_bar5.image(tmbet5, use_column_width=500)
    st.header('3BET-CALL: Desde SB')
    tmbet_bar6 = st.beta_expander('3BET-CALL-MULTIWAY: SB vs BTN vs CO')
    tmbet6 = Image.open('3BET-CALL_MULTIWAY_SBvsBTNvsCO.png')
    tmbet_bar6.image(tmbet6, use_column_width=500)
    tmbet_bar7 = st.beta_expander('3BET-CALL-MULTIWAY: SB vs CO vs EP')
    tmbet7 = Image.open('3BET-CALL_MULTIWAY_SBvsCOvsEP.png')
    tmbet_bar7.image(tmbet7, use_column_width=500)
    st.header('3BET-CALL: Desde BTN')
    tmbet_bar8 = st.beta_expander('3BET-CALL-MULTIWAY: BTN vs CO vs EP')
    tmbet8 = Image.open('3BET-CALL_MULTIWAY_BTNvsCOvsEP.png')
    tmbet_bar8.image(tmbet8, use_column_width=500)
    tmbet_bar9 = st.beta_expander('3BET-CALL-MULTIWAY: BTN vs MP vs UTG')
    tmbet9 = Image.open('3BET-CALL_MULTIWAY_BTNvsMPvsUTG.png')
    tmbet_bar9.image(tmbet9, use_column_width=500)
    st.pyplot()
    
if preflop_selector == 'Cold4Bet':
    st.header('COLD4BET: Desde BB')
    coldbet_bar = st.beta_expander('IP COLD4BET: BB vs SB vs BTN')
    coldbet = Image.open('COLD4BET_BBvsSBvsBTN.png')
    coldbet_bar.image(coldbet, use_column_width=500)
    coldbet_bar1 = st.beta_expander('IP COLD4BET: BB vs SB vs CO')
    coldbet1 = Image.open('COLD4BET_BBvsSBvsCO.png')
    coldbet_bar1.image(coldbet1, use_column_width=500)
    coldbet_bar2 = st.beta_expander('IP COLD4BET: BB vs SB vs EP')
    coldbet2 = Image.open('COLD4BET_BBvsSBvsEP.png')
    coldbet_bar2.image(coldbet2, use_column_width=500)
    coldbet_bar3 = st.beta_expander('OOP COLD4BET: BB vs BTN vs CO')
    coldbet3 = Image.open('COLD4BET_BBvsBTNvsCO_OOP.png')
    coldbet_bar3.image(coldbet3, use_column_width=500)
    coldbet_bar4 = st.beta_expander('OOP COLD4BET: BB vs BTN vs EP')
    coldbet4 = Image.open('COLD4BET_BBvsBTNvsEP_OOP.png')
    coldbet_bar4.image(coldbet4, use_column_width=500)
    coldbet_bar5 = st.beta_expander('OOP COLD4BET: BB vs CO vs EP')
    coldbet5 = Image.open('COLD4BET_BBvsCOvsEP_OOP.png')
    coldbet_bar5.image(coldbet5, use_column_width=500)
    coldbet_bar6 = st.beta_expander('OOP COLD4BET: BB vs MP vs UTG')
    coldbet6 = Image.open('COLD4BET_BBvsMPvsUTG_OOP.png')
    coldbet_bar6.image(coldbet6, use_column_width=500)
    st.header('COLD4BET: Desde SB')
    coldbet_bar7 = st.beta_expander('OOP COLD4BET: SB vs BTN vs CO')
    coldbet7 = Image.open('COLD4BET_SBvsBTNvsCO.png')
    coldbet_bar7.image(coldbet7, use_column_width=500)
    coldbet_bar8 = st.beta_expander('OOP COLD4BET: SB vs BTN vs EP')
    coldbet8 = Image.open('COLD4BET_SBvsBTNvsEP.png')
    coldbet_bar8.image(coldbet8, use_column_width=500)
    coldbet_bar9 = st.beta_expander('OOP COLD4BET: SB vs CO vs EP')
    coldbet9 = Image.open('COLD4BET_SBvsCOvsEP.png')
    coldbet_bar9.image(coldbet9, use_column_width=500)
    coldbet_bar10 = st.beta_expander('OOP COLD4BET: SB vs MP vs UTG')
    coldbet10 = Image.open('COLD4BET_SBvsMPvsUTG.png')
    coldbet_bar10.image(coldbet10, use_column_width=500)
    st.header('COLD4BET: Desde BTN+')
    coldbet_bar11 = st.beta_expander('IP COLD4BET: BTN vs CO vs EP')
    coldbet11 = Image.open('COLD4BET_BTNvsCOvsEP.png')
    coldbet_bar11.image(coldbet11, use_column_width=500)
    coldbet_bar12 = st.beta_expander('IP COLD4BET: BTN vs MP vs UTG')
    coldbet12 = Image.open('COLD4BET_BTNvsMPvsUTG.png')
    coldbet_bar12.image(coldbet12, use_column_width=500)
    coldbet_bar13 = st.beta_expander('IP COLD4BET: CO vs MP vs UTG')
    coldbet13 = Image.open('COLD4BET_COvsMPvsUTG.png')
    coldbet_bar13.image(coldbet13, use_column_width=500)
    st.pyplot()

if preflop_selector == 'VS Cold4Bet':
    st.header('Desde SB')
    vscoldbet_bar = st.beta_expander('VS COLD4BET(AGRO): SB vs BTN vs BB(Call4Bet)')
    vscoldbet = Image.open('VS_COLD4BET_SBvsBTNvsBBC4B(AGRO).png')
    vscoldbet_bar.image(vscoldbet, use_column_width=500)
    vscoldbet_bar1 = st.beta_expander('VS COLD4BET(TIGHT): SB vs BTN vs BB(Call4Bet)')
    vscoldbet1 = Image.open('VS_COLD4BET_SBvsBTNvsBBC4B(TIGHT).png')
    vscoldbet_bar1.image(vscoldbet1, use_column_width=500)
    vscoldbet_bar2 = st.beta_expander('VS COLD4BET(TIGHT): SB vs BTN vs BB(Call4Bet)')
    vscoldbet2 = Image.open('VS_COLD4BET_SBvsBTNvsBBC4B(TIGHT).png')
    vscoldbet_bar2.image(vscoldbet2, use_column_width=500)
    vscoldbet_bar3 = st.beta_expander('VS COLD4BET: SB vs BTN vs BB(Call4Bet)')
    vscoldbet3 = Image.open('VS_COLD4BET_SBvsBTNvsBBC4B.png')
    vscoldbet_bar3.image(vscoldbet3, use_column_width=500)
    st.header('Desde BTN+')
    vscoldbet_bar4 = st.beta_expander('VS COLD4BET: BTN vs COLD4BET')
    vscoldbet4 = Image.open('VS_COLD4BET_BTNvsCOLD4BET.png')
    vscoldbet_bar4.image(vscoldbet4, use_column_width=500)
    vscoldbet_bar5 = st.beta_expander('VS COLD4BET: CO vs COLD4BET')
    vscoldbet5 = Image.open('VS_COLD4BET_COvsCOLD4BET.png')
    vscoldbet_bar5.image(vscoldbet5, use_column_width=500)
    
if preflop_selector == 'Call3Bet-4Bet':
    st.header('CALL3BET o 4BET OOP')
    call3bet_bar = st.beta_expander('OOP: VS 15%')
    call3bet = Image.open('CALL3BETvs15%_OOP.png')
    call3bet_bar.image(call3bet, use_column_width=500)
    call3bet_bar1 = st.beta_expander('OOP: VS 12%')
    call3bet1 = Image.open('CALL3BETvs12%_OOP.png')
    call3bet_bar1.image(call3bet1, use_column_width=500)
    call3bet_bar2 = st.beta_expander('OOP: VS 10%')
    call3bet2 = Image.open('CALL3BETvs15%_OOP.png')
    call3bet_bar2.image(call3bet2, use_column_width=500)
    call3bet_bar3 = st.beta_expander('OOP: VS 7.4%')
    call3bet3 = Image.open('CALL3BETvs7.4%_OOP.png')
    call3bet_bar3.image(call3bet3, use_column_width=500)
    call3bet_bar4 = st.beta_expander('OOP: VS 4.8%')
    call3bet4 = Image.open('CALL3BETvs4.8%_OOP.png')
    call3bet_bar4.image(call3bet4, use_column_width=500)
    st.pyplot()
